<style type="text/css">
/* The "!important" are to override the tablesorter styling */

table {
  width: auto !important;
  font-size: 14px !important;
}

table.booktabs {
    font-family: Charter, "Bitstream Charter", serif;
    border-collapse: collapse;
    border-bottom: 2px solid #333;
    border-top: 2px solid #333;
}

table.booktabs th {
    font-weight: normal;
    padding: 0px 10px;
    vertical-align: bottom;
}

table.booktabs td {
    padding: 0px 10px;
    vertical-align: top;
}

table.booktabs tbody tr { border-bottom: 1px dotted #ccc; }
table.booktabs thead th { border-bottom: 1px solid #333 !important; }
table.booktabs tfoot th { border-top: 1px solid #333; }

table.wikitable {
  border-collapse: collapse;
  background-color: #f9f9f9;
  font-family: Helvetica, sans-serif;
}

table.wikitable th {
  background-color: #f2f2f2;
  border: 1px solid #aaaaaa !important;
  padding: 5px 10px;
}

table.wikitable td {
  border: 1px solid #aaaaaa;
  padding: 5px 10px;
}
</style>
